bug:
  - '**/*.js'
  - '**/*.css'
  - '**/*.html'

documentation:
  - '**/*.md'
  - '**/README.md'
  - '**/docs/**'

enhancement:
  - '**/*.ts'
  - '**/feature_request.yml'

gssoc25:
  - '**/*'

level1:
  - '**/level1/**'

level2:
  - '**/level2/**'

level3:
  - '**/level3/**'

github:
  - '.github/**'
