bug:
  - '**/*.js'
  - '**/*.css'
  - '**/*.html'

enhancement:
  - '**/*.ts'
  - '**/*.yml'

documentation:
  - '**/*.md'
  - '**/README.md'
  - '**/docs/**'

github:
  - '.github/**'

gssoc25:
  - '**/*'
