bug:
  - '**/*.js'
  - '**/*.css'
  - '**/*.html'
  - '**/*.ts'

enhancement:
  - '**/feature_request.yml'
  - '**/enhancement.yml'

documentation:
  - '**/*.md'
  - '**/README.md'
  - '**/LEARN.md'
  - '**/docs/**'

github:
  - '.github/**'

ci:
  - '.github/workflows/**'
