name: Greet Every Contributor
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  greet-issue:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - name: Greet new issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: "🎉 Welcome! Thanks for opening your issue! The team will review it soon."
            });
  greet-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Greet new pull request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: "🚀 Thanks for your pull request! We’ll review it soon."
            });
